// @audio/spectral — spectral features & editing umbrella re-exporting every @audio/spectral-* atom.

export { default as centroid } from '@audio/spectral-centroid'
export { default as spread } from '@audio/spectral-spread'
export { default as flatness } from '@audio/spectral-flatness'
export { default as rolloff } from '@audio/spectral-rolloff'
export { default as flux } from '@audio/spectral-flux'
export { default as slope } from '@audio/spectral-slope'
export { default as crest } from '@audio/spectral-crest'
export { default as mfcc } from '@audio/spectral-mfcc'
export { default as ltas } from '@audio/spectral-ltas'
export { default as edit } from '@audio/spectral-edit'
export { default as freeze } from '@audio/spectral-freeze'
export { default as contrast } from '@audio/spectral-contrast'
export { default as harmonics } from '@audio/spectral-harmonics'
export { default as cqt } from '@audio/spectral-cqt'
export { default as zcr } from '@audio/spectral-zcr'
export { default as target, deviation, smooth } from '@audio/spectral-target'

export { scatterGated, scatterLocked, lockPhase, findPeaks, nearestPeak, makeFrameRatio, wrapPhase, WIN_GAIN } from '@audio/spectral-pvoc'
